// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/09/2024, 11:09:17
const configMerger = require("/Users/mariojosegoes/Documents/YoyoWeather/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/mariojosegoes/Documents/YoyoWeather/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariojosegoes/Documents/YoyoWeather/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariojosegoes/Documents/YoyoWeather/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariojosegoes/Documents/YoyoWeather/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariojosegoes/Documents/YoyoWeather/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariojosegoes/Documents/YoyoWeather/plugins/**/*.{js,ts,mjs}","/Users/mariojosegoes/Documents/YoyoWeather/composables/**/*.{js,ts,mjs}","/Users/mariojosegoes/Documents/YoyoWeather/utils/**/*.{js,ts,mjs}","/Users/mariojosegoes/Documents/YoyoWeather/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mariojosegoes/Documents/YoyoWeather/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mariojosegoes/Documents/YoyoWeather/app.config.{js,ts,mjs}"] }));

module.exports = config
